# frozen_string_literal: true

source "https://rubygems.org"

ruby RUBY_VERSION

gem "decidim", "0.20.0"
gem 'decidim-admin', "0.20.0"
gem 'decidim-proposals', "0.20.0"
gem 'decidim-surveys', "0.20.0"
gem 'decidim-consultations', "0.20.0"
gem 'decidim-comments', "0.20.0"


gem 'wicked_pdf', '~> 1.4'
gem 'wkhtmltopdf-binary', '~> 0.12.4'
gem 'decidim-initiatives', "0.20.0"


# gem 'decidim-api', "0.20.0"
gem 'decidim-suomifi', git: "https://github.com/mainio/decidim-module-suomifi"
gem 'omniauth-saml', "1.10.1"
gem 'savon', '~> 2.12.0'
gem 'omniauth-keycloak'
# gem "decidim-initiatives", "0.20.0"
# gem "decidim-sortitions", "0.20.0"
# gem 'omniauth-decidim', git: 'https://github.com/decidim/omniauth-decidim'
 gem 'omniauth'
# gem 'omniauth-lastfm'
gem 'ruby-saml', '~> 1.11.0'

gem "bootsnap", "~> 1.3"

gem "puma", "~> 3.12.2"
gem "uglifier", "~> 4.1"

gem "faker", "~> 1.9"

group :development, :test do
  gem "byebug", "~> 11.0", platform: :mri

  gem "decidim-dev", "0.20.0"
end

group :development do
  gem "letter_opener_web", "~> 1.3"
  gem "listen", "~> 3.1"
  gem "spring", "~> 2.0"
  gem "spring-watcher-listen", "~> 2.0"
  gem "web-console", "~> 3.5"
end
